#!/usr/bin/env python3
"""
Real code generator: Reads contracts/registry/pulse-types.json,
and generates Rust PulseType enum and metadata in ryu-node-proto.
"""

from __future__ import annotations

import json
from pathlib import Path


def generate_rust_proto() -> Path:
    repo_root = Path(__file__).resolve().parents[3]
    registry_file = repo_root / "contracts" / "registry" / "pulse-types.json"
    output_dir = repo_root / "node_runtime" / "crates" / "ryu-node-proto" / "src"
    output_dir.mkdir(parents=True, exist_ok=True)
    output_file = output_dir / "generated.rs"

    with open(registry_file, "r", encoding="utf-8") as f:
        registry_data = json.load(f)

    types = registry_data.get("types", [])

    lines = [
        "// Auto-generated by contracts/codegen/rust/generate_rust_proto.py",
        "// Source: contracts/registry/pulse-types.json",
        "// DO NOT EDIT DIRECTLY.",
        "",
        "#[derive(Debug, Clone, PartialEq, Eq, Hash)]",
        "pub enum PulseType {",
    ]

    for item in types:
        ptype = item["type"]
        variant_name = "".join(part.capitalize() for part in ptype.replace(".", "_").split("_"))
        lines.append(f'    /// {item.get("description", "")}')
        lines.append(f"    {variant_name},")

    lines.extend([
        "}",
        "",
        "impl PulseType {",
        "    pub fn as_str(&self) -> &'static str {",
        "        match self {",
    ])

    for item in types:
        ptype = item["type"]
        variant_name = "".join(part.capitalize() for part in ptype.replace(".", "_").split("_"))
        lines.append(f'            PulseType::{variant_name} => "{ptype}",')

    lines.extend([
        "        }",
        "    }",
        "",
        "    pub fn parse_str(s: &str) -> Option<Self> {",
        "        match s {",
    ])

    for item in types:
        ptype = item["type"]
        variant_name = "".join(part.capitalize() for part in ptype.replace(".", "_").split("_"))
        lines.append(f'            "{ptype}" => Some(PulseType::{variant_name}),')

    lines.extend([
        "            _ => None,",
        "        }",
        "    }",
        "}",
    ])

    output_file.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[rust-codegen] Generated {len(types)} Rust pulse variants in {output_file}")
    return output_file


if __name__ == "__main__":
    generate_rust_proto()

