// Auto-generated by contracts/codegen/rust/generate_rust_proto.py
// Source: contracts/registry/pulse-types.json
// DO NOT EDIT DIRECTLY.

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum PulseType {
    /// Emitted when a new Space is instantiated.
    SpaceCreated,
    /// Emitted when an existing Space is restored from checkpoint.
    SpaceRestored,
    /// Emitted when a Space finishes execution or reaches its goal.
    SpaceCompleted,
    /// Emitted when a Space's artifacts and timeline are archived.
    SpaceArchived,
    /// Emitted when Space spend exhausts or breaches budget limits.
    SpaceBudgetExceeded,
    /// Emitted when a Command is converted into a structured Goal Spec.
    GoalDefined,
    /// Emitted when an initial versioned Task Graph is planned.
    PlanCreated,
    /// Emitted when a plan delta modification is proposed.
    PlanDelta,
    /// Emitted when a concurrent replan loses CAS commit to a winning delta.
    PlanVersionSuperseded,
    /// Emitted when a Task Graph node is assigned to an agent or worker.
    TaskAssigned,
    /// Emitted when an assigned task begins execution.
    TaskStarted,
    /// Emitted when a task finishes successfully with an artifact reference.
    TaskCompleted,
    /// Emitted when a task encounters a transient or terminal failure.
    TaskFailed,
    /// Emitted when a transient task failure triggers a retry attempt.
    TaskRetried,
    /// Emitted when a worker invokes an underlying tool capability.
    WorkerToolCalled,
    /// Emitted when a tool invocation completes successfully.
    WorkerToolSucceeded,
    /// Emitted when a tool invocation fails.
    WorkerToolFailed,
    /// Emitted when the orchestrator applies a plan delta revision.
    OrchestratorPlanDelta,
    /// Emitted when the orchestrator reassigns a task between execution roles.
    OrchestratorReassigned,
    /// Emitted when a worker or agent requests a leased resource.
    ResourceRequested,
    /// Emitted when the Resource Manager grants a lease on a resource.
    ResourceGranted,
    /// Emitted when a resource request is rejected.
    ResourceDenied,
    /// Emitted when a held resource lease is relinquished.
    ResourceReleased,
    /// Emitted when a resource request contends for an existing lease and is queued.
    ResourceConflict,
    /// Emitted when a requester exceeds rate quotas and requests are queued; backpressure, not failure.
    RateLimited,
    /// Emitted when a capability grant on a remote node runtime is issued.
    NodeCapabilityGranted,
    /// Emitted when an active node capability grant is revoked.
    NodeCapabilityRevoked,
    /// Emitted when a node runtime misses heartbeats beyond TTL.
    NodeOffline,
    /// Emitted when an offline node reconnects and re-establishes its lease.
    NodeReconnected,
    /// Emitted when untrusted external content enters the pulse stream.
    SecurityTaintDetected,
    /// Emitted when human approval clears taint forward for a correlation_id.
    SecurityTaintCleared,
    /// Emitted when an authorized approver approves a high-risk capability grant.
    SecurityGrantApproved,
    /// Emitted when a capability grant request is denied.
    SecurityGrantDenied,
    /// Emitted when Space-local knowledge is proposed for global promotion.
    KnowledgePromotionRequested,
    /// Emitted when promotion to global knowledge is approved.
    KnowledgePromotionApproved,
    /// Emitted when promotion to global knowledge is rejected by validator or approver.
    KnowledgePromotionRejected,
    /// Emitted when memory state (task, agent, or space scope) is updated.
    MemoryUpdated,
    /// Emitted when structured experience including counterfactual is stored.
    ExperienceStored,
}

impl PulseType {
    pub fn as_str(&self) -> &'static str {
        match self {
            PulseType::SpaceCreated => "space.created",
            PulseType::SpaceRestored => "space.restored",
            PulseType::SpaceCompleted => "space.completed",
            PulseType::SpaceArchived => "space.archived",
            PulseType::SpaceBudgetExceeded => "space.budget.exceeded",
            PulseType::GoalDefined => "goal.defined",
            PulseType::PlanCreated => "plan.created",
            PulseType::PlanDelta => "plan.delta",
            PulseType::PlanVersionSuperseded => "plan.version.superseded",
            PulseType::TaskAssigned => "task.assigned",
            PulseType::TaskStarted => "task.started",
            PulseType::TaskCompleted => "task.completed",
            PulseType::TaskFailed => "task.failed",
            PulseType::TaskRetried => "task.retried",
            PulseType::WorkerToolCalled => "worker.tool.called",
            PulseType::WorkerToolSucceeded => "worker.tool.succeeded",
            PulseType::WorkerToolFailed => "worker.tool.failed",
            PulseType::OrchestratorPlanDelta => "orchestrator.plan.delta",
            PulseType::OrchestratorReassigned => "orchestrator.reassigned",
            PulseType::ResourceRequested => "resource.requested",
            PulseType::ResourceGranted => "resource.granted",
            PulseType::ResourceDenied => "resource.denied",
            PulseType::ResourceReleased => "resource.released",
            PulseType::ResourceConflict => "resource.conflict",
            PulseType::RateLimited => "rate.limited",
            PulseType::NodeCapabilityGranted => "node.capability.granted",
            PulseType::NodeCapabilityRevoked => "node.capability.revoked",
            PulseType::NodeOffline => "node.offline",
            PulseType::NodeReconnected => "node.reconnected",
            PulseType::SecurityTaintDetected => "security.taint.detected",
            PulseType::SecurityTaintCleared => "security.taint.cleared",
            PulseType::SecurityGrantApproved => "security.grant.approved",
            PulseType::SecurityGrantDenied => "security.grant.denied",
            PulseType::KnowledgePromotionRequested => "knowledge.promotion.requested",
            PulseType::KnowledgePromotionApproved => "knowledge.promotion.approved",
            PulseType::KnowledgePromotionRejected => "knowledge.promotion.rejected",
            PulseType::MemoryUpdated => "memory.updated",
            PulseType::ExperienceStored => "experience.stored",
        }
    }

    pub fn parse_str(s: &str) -> Option<Self> {
        match s {
            "space.created" => Some(PulseType::SpaceCreated),
            "space.restored" => Some(PulseType::SpaceRestored),
            "space.completed" => Some(PulseType::SpaceCompleted),
            "space.archived" => Some(PulseType::SpaceArchived),
            "space.budget.exceeded" => Some(PulseType::SpaceBudgetExceeded),
            "goal.defined" => Some(PulseType::GoalDefined),
            "plan.created" => Some(PulseType::PlanCreated),
            "plan.delta" => Some(PulseType::PlanDelta),
            "plan.version.superseded" => Some(PulseType::PlanVersionSuperseded),
            "task.assigned" => Some(PulseType::TaskAssigned),
            "task.started" => Some(PulseType::TaskStarted),
            "task.completed" => Some(PulseType::TaskCompleted),
            "task.failed" => Some(PulseType::TaskFailed),
            "task.retried" => Some(PulseType::TaskRetried),
            "worker.tool.called" => Some(PulseType::WorkerToolCalled),
            "worker.tool.succeeded" => Some(PulseType::WorkerToolSucceeded),
            "worker.tool.failed" => Some(PulseType::WorkerToolFailed),
            "orchestrator.plan.delta" => Some(PulseType::OrchestratorPlanDelta),
            "orchestrator.reassigned" => Some(PulseType::OrchestratorReassigned),
            "resource.requested" => Some(PulseType::ResourceRequested),
            "resource.granted" => Some(PulseType::ResourceGranted),
            "resource.denied" => Some(PulseType::ResourceDenied),
            "resource.released" => Some(PulseType::ResourceReleased),
            "resource.conflict" => Some(PulseType::ResourceConflict),
            "rate.limited" => Some(PulseType::RateLimited),
            "node.capability.granted" => Some(PulseType::NodeCapabilityGranted),
            "node.capability.revoked" => Some(PulseType::NodeCapabilityRevoked),
            "node.offline" => Some(PulseType::NodeOffline),
            "node.reconnected" => Some(PulseType::NodeReconnected),
            "security.taint.detected" => Some(PulseType::SecurityTaintDetected),
            "security.taint.cleared" => Some(PulseType::SecurityTaintCleared),
            "security.grant.approved" => Some(PulseType::SecurityGrantApproved),
            "security.grant.denied" => Some(PulseType::SecurityGrantDenied),
            "knowledge.promotion.requested" => Some(PulseType::KnowledgePromotionRequested),
            "knowledge.promotion.approved" => Some(PulseType::KnowledgePromotionApproved),
            "knowledge.promotion.rejected" => Some(PulseType::KnowledgePromotionRejected),
            "memory.updated" => Some(PulseType::MemoryUpdated),
            "experience.stored" => Some(PulseType::ExperienceStored),
            _ => None,
        }
    }
}
