"""RYU AI Base Agent State Machine.

The Agent is a deterministic state machine over Pulse subscriptions and context;
the LLM acts as the transition function during THINKING (docs/Architecture §7, ROADMAP Phase 5).
The LLM never directly receives authority or mutates state (ADR-0010, Corrections 4, 8, 10).

spec §7 (Cognitive Layer), ROADMAP Phase 5, AGENT-001 — Phase 5
"""

from __future__ import annotations

import json
import threading
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Protocol

from ryu.pulse_bus.pulse import Pulse

from agents.context import ContextEntry, ContextManager, ContextScope
from llm.provider import LLMProvider, LLMRequest, LLMResponse, MockLLMProvider
from llm.recorder import LLMRecord, LLMRecorder


class PulsePublisher(Protocol):
    def publish(self, pulse: Pulse) -> Pulse: ...


class AgentState(str, Enum):
    """Explicit deterministic Agent lifecycle states (ADR-0010, Prompt §5)."""

    IDLE = "IDLE"
    THINKING = "THINKING"
    PROPOSING = "PROPOSING"
    WAITING = "WAITING"
    EXECUTING = "EXECUTING"
    OBSERVING = "OBSERVING"
    REFLECTING = "REFLECTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


@dataclass
class AgentProposal:
    """Structured proposal generated by an Agent for evaluation by deterministic authority."""

    intent: str
    reasoning: str
    requested_action: str
    parameters: dict[str, Any] = field(default_factory=dict)
    confidence: float = 1.0
    required_capabilities: list[str] = field(default_factory=list)
    is_valid: bool = True
    rejection_reason: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "intent": self.intent,
            "reasoning": self.reasoning,
            "requested_action": self.requested_action,
            "parameters": dict(self.parameters),
            "confidence": self.confidence,
            "required_capabilities": list(self.required_capabilities),
            "is_valid": self.is_valid,
            "rejection_reason": self.rejection_reason,
        }


class ProposalValidator:
    """Enforces constitutional non-authority on Agent proposals (Corrections 4, 8, 10).

    The LLM/Agent must NEVER be able to:
    - Mutate the authoritative TaskGraph directly
    - Allocate resources directly or mint leases
    - Bypass Space budget or Admission Control
    - Approve human gates or self-authorize
    - Resolve or extract raw secrets directly
    - Cross Space isolation boundaries
    - Execute arbitrary unadmitted shell or network commands
    """

    # Forbidden action names that attempt direct authority bypass
    FORBIDDEN_ACTIONS = frozenset(
        {
            "modify_authoritative_plan",
            "edit_task_graph",
            "allocate_gpu",
            "direct_resource_alloc",
            "mint_lease",
            "issue_lease",
            "ignore_budget",
            "bypass_budget",
            "approve_human_gate",
            "self_approve",
            "read_secret",
            "resolve_secret",
            "modify_space",
            "cross_space_action",
            "execute_shell",
            "raw_network",
        }
    )

    def __init__(
        self,
        current_space_id: str,
        allowed_capabilities: set[str] | list[str] | None = None,
    ) -> None:
        self.current_space_id = current_space_id
        self.allowed_capabilities = (
            set(allowed_capabilities) if allowed_capabilities is not None else None
        )

    def validate(self, proposal: AgentProposal) -> tuple[bool, str | None]:
        """Validate an AgentProposal against constitutional authority invariants."""
        # 1. Check required fields
        if not proposal.intent or not proposal.requested_action:
            return False, "terminal.invalid_params: Missing required intent or requested_action"

        # 2. Check forbidden direct authority bypass actions
        action = proposal.requested_action.lower().strip()
        if action in self.FORBIDDEN_ACTIONS:
            return (
                False,
                f"terminal.permission_denied: Forbidden direct authority action '{action}'",
            )

        # 3. Check for unauthorized secret resolution
        if "secret" in action or "secret" in str(proposal.parameters).lower():
            if action in ("read_secret", "resolve_secret", "extract_secret"):
                return (
                    False,
                    "terminal.permission_denied: Agent has no direct SecretResolver authority",
                )

        # 4. Check parameter types
        if not isinstance(proposal.parameters, dict):
            return False, "terminal.invalid_params: parameters must be a dictionary"

        # 5. Check for Space boundary traversal in parameters
        target_space = proposal.parameters.get("space_id")
        if target_space and target_space != self.current_space_id:
            return False, (
                f"terminal.permission_denied: Cross-space reference '{target_space}' "
                f"violates Space isolation (current: '{self.current_space_id}')"
            )

        # 6. Check allowed capabilities if policy configured (Scenario 14)
        if self.allowed_capabilities is not None:
            for cap in proposal.required_capabilities:
                if cap not in self.allowed_capabilities:
                    return False, f"terminal.permission_denied: Capability '{cap}' not permitted"

        return True, None


class BaseAgent:
    """Deterministic Agent state machine operating under Space authority (docs/Architecture §7).

    Invariants (ADR-0010, Corrections 4, 8, 10):
    - Explicit state transitions logged deterministically.
    - LLM output is converted into an AgentProposal and validated before application.
    - Contains zero direct SecretResolver authority.
    - All capability executions route through Kernel Admission.
    """

    def __init__(
        self,
        agent_id: str,
        space_id: str,
        provider: LLMProvider | None = None,
        recorder: LLMRecorder | None = None,
        context_mgr: ContextManager | None = None,
        bus: PulsePublisher | None = None,
        model: str = "mock-agent-v1",
        allowed_capabilities: set[str] | list[str] | None = None,
    ) -> None:
        self.agent_id = agent_id
        self.space_id = space_id
        self.provider = provider or MockLLMProvider()
        self.recorder = recorder
        self.context_mgr = context_mgr or ContextManager(space_id=space_id)
        self.bus = bus
        self.model = model

        self._lock = threading.Lock()
        self.state: AgentState = AgentState.IDLE
        self.state_history: list[tuple[AgentState, datetime]] = [
            (AgentState.IDLE, datetime.now(timezone.utc))
        ]
        self.proposals: list[AgentProposal] = []
        self.validator = ProposalValidator(
            current_space_id=space_id,
            allowed_capabilities=allowed_capabilities,
        )

    def transition_to(self, new_state: AgentState) -> None:
        """Deterministically transition to a new lifecycle state and record history."""
        with self._lock:
            self.state = new_state
            self.state_history.append((new_state, datetime.now(timezone.utc)))

    def step(
        self,
        task_id: str,
        instruction: str,
        correlation_id: str | None = None,
    ) -> AgentProposal:
        """Execute one cognitive step through the lifecycle states:
        IDLE -> THINKING -> PROPOSING -> WAITING -> EXECUTING
        -> OBSERVING -> REFLECTING -> COMPLETED.
        """
        corr_id = correlation_id or f"corr-{self.agent_id}-{task_id}"

        # 1. Transition to THINKING
        self.transition_to(AgentState.THINKING)

        # 2. Append instruction to context
        entry = ContextEntry(
            turn_id=f"turn-{self.agent_id}-{task_id}",
            scope=ContextScope.TASK,
            content=instruction,
            metadata={"task_id": task_id},
        )
        self.context_mgr.append_entry(
            scope=ContextScope.TASK,
            entry=entry,
            agent_id=self.agent_id,
            task_id=task_id,
            caller_scope=ContextScope.TASK,
        )

        # 3. Assemble visible context
        visible_context = self.context_mgr.get_effective_context(self.agent_id, task_id)
        context_messages = [
            {"role": "system", "content": f"Space: {self.space_id}, Agent: {self.agent_id}"},
            {"role": "user", "content": instruction},
        ]
        for ctx in visible_context[-5:]:
            context_messages.append(
                {"role": "assistant" if ctx.pinned else "user", "content": ctx.content}
            )

        # 4. Invoke LLM provider (stochastic transition function)
        req = LLMRequest(
            request_id=f"req-{self.agent_id}-{task_id}-{len(self.proposals) + 1}",
            correlation_id=corr_id,
            space_id=self.space_id,
            agent_id=self.agent_id,
            model=self.model,
            provider=getattr(self.provider, "provider_name", "llm_provider"),
            messages=context_messages,
        )

        try:
            resp: LLMResponse = self.provider.complete(req)
        except Exception as exc:
            self.transition_to(AgentState.FAILED)
            err_proposal = AgentProposal(
                intent="failure_handling",
                reasoning=str(exc),
                requested_action="report_failure",
                parameters={"error": str(exc)},
                is_valid=False,
                rejection_reason=f"LLM failure: {exc}",
            )
            self.proposals.append(err_proposal)
            return err_proposal

        # 5. Record call if recorder configured
        if self.recorder:
            record = LLMRecord(
                call_id=req.request_id,
                correlation_id=corr_id,
                space_id=self.space_id,
                agent_id=self.agent_id,
                provider=req.provider,
                model=req.model,
                request=req,
                response=resp,
                usage=resp.usage,
                status=resp.status,
                error=resp.error,
            )
            self.recorder.record(record)

        # 6. Parse structured proposal from response
        proposal = self._parse_proposal(resp)

        # 7. Deterministic validation (Corrections 4, 8, 10)
        is_valid, reason = self.validator.validate(proposal)
        proposal.is_valid = is_valid
        proposal.rejection_reason = reason

        if not is_valid:
            self.transition_to(AgentState.FAILED)
            self.proposals.append(proposal)
            return proposal

        # 8. Valid proposal: transition to PROPOSING
        self.transition_to(AgentState.PROPOSING)
        self.proposals.append(proposal)

        # 9. Enter downstream deterministic lifecycle phases
        self.transition_to(AgentState.WAITING)
        self.transition_to(AgentState.EXECUTING)
        self.transition_to(AgentState.OBSERVING)
        self.transition_to(AgentState.REFLECTING)
        self.transition_to(AgentState.COMPLETED)

        return proposal

    def _parse_proposal(self, resp: LLMResponse) -> AgentProposal:
        """Parse structured output or content into a typed AgentProposal."""
        if resp.status != "ok" or resp.error is not None:
            err_msg = resp.error.message if resp.error else "Provider returned failed status"
            return AgentProposal(
                intent="failure_handling",
                reasoning=err_msg,
                requested_action="report_failure",
                parameters={"error": err_msg},
                is_valid=False,
                rejection_reason=f"LLM failure: {err_msg}",
            )

        if resp.structured_output:
            so = resp.structured_output
            return AgentProposal(
                intent=str(so.get("intent", "general_intent")),
                reasoning=str(so.get("reasoning", "")),
                requested_action=str(so.get("requested_action", "")),
                parameters=dict(so.get("parameters", {})),
                confidence=float(so.get("confidence", 1.0)),
                required_capabilities=list(so.get("required_capabilities", [])),
            )

        # Fallback: attempt to parse JSON from content
        try:
            data = json.loads(resp.content)
            if isinstance(data, dict):
                return AgentProposal(
                    intent=str(data.get("intent", "general_intent")),
                    reasoning=str(data.get("reasoning", "")),
                    requested_action=str(data.get("requested_action", "")),
                    parameters=dict(data.get("parameters", {})),
                    confidence=float(data.get("confidence", 1.0)),
                    required_capabilities=list(data.get("required_capabilities", [])),
                )
        except Exception:
            pass

        # Free-form text: treated as untrusted data, never as direct instruction (Correction 8)
        return AgentProposal(
            intent="unstructured_cognition",
            reasoning="Model returned free-form text",
            requested_action="synthesize_data",
            parameters={"raw_content": resp.content},
        )
