#!/usr/bin/env python3
"""
Real code generator: Reads contracts/registry/pulse-types.json and payload schemas,
and generates Python PulseType enum and typed constants.
"""

from __future__ import annotations

import json
from pathlib import Path


def generate_pulse_models() -> Path:
    repo_root = Path(__file__).resolve().parents[3]
    registry_file = repo_root / "contracts" / "registry" / "pulse-types.json"
    output_dir = repo_root / "contracts" / "codegen" / "python" / "generated"
    output_dir.mkdir(parents=True, exist_ok=True)
    output_file = output_dir / "pulse_models.py"

    with open(registry_file, "r", encoding="utf-8") as f:
        registry_data = json.load(f)

    types = registry_data.get("types", [])

    lines = [
        "# Auto-generated by contracts/codegen/python/generate_pulse_models.py",
        "# Source: contracts/registry/pulse-types.json",
        "# DO NOT EDIT DIRECTLY.",
        "",
        "from enum import Enum",
        "from typing import Final",
        "",
        "",
        "class PulseType(str, Enum):",
    ]

    for item in types:
        ptype = item["type"]
        enum_name = ptype.upper().replace(".", "_")
        lines.append(f'    {enum_name} = "{ptype}"')

    lines.extend([
        "",
        "ALL_PULSE_TYPES: Final[set[str]] = {",
    ])
    for item in types:
        lines.append(f'    "{item["type"]}",')
    lines.append("}")

    lines.extend([
        "",
        "PULSE_DEFAULT_SEVERITIES: Final[dict[str, str]] = {",
    ])
    for item in types:
        lines.append(f'    "{item["type"]}": "{item.get("default_severity", "info")}",')
    lines.append("}")

    output_file.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[python-codegen] Successfully generated {len(types)} pulse types in {output_file}")
    return output_file


if __name__ == "__main__":
    generate_pulse_models()

