"""Worker contract definitions, data types, and failure taxonomy mapping.

spec §7 (Execution Layer), §10 (Prompt-Injection & Taint Model), §14, §16,
CONTRACT_MATRIX WORKER-001..WORKER-005, TAINT-001, SECRET-004 — Phase 6
ADR-0013, ADR-0014, ADR-0015, ADR-0016
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any


class WorkerState(str, Enum):
    """Deterministic lifecycle states for a capability Worker."""

    CREATED = "created"
    READY = "ready"
    ADMITTED = "admitted"
    STARTING = "starting"
    RUNNING = "running"
    OBSERVING = "observing"
    COMPLETED = "completed"

    # Terminal failure states
    FAILED = "failed"
    TIMED_OUT = "timed_out"
    RESOURCE_EXHAUSTED = "resource_exhausted"
    SANDBOX_VIOLATION = "sandbox_violation"
    CANCELLED = "cancelled"


@dataclass(frozen=True)
class WorkerIdentity:
    """Immutable identity of a capability worker instance."""

    worker_id: str
    capability: str
    space_id: str
    version: str = "1.0.0"

    def to_dict(self) -> dict[str, str]:
        return {
            "worker_id": self.worker_id,
            "capability": self.capability,
            "space_id": self.space_id,
            "version": self.version,
        }


@dataclass
class ExecutionLimits:
    """Execution quotas and limits for a sandboxed capability execution."""

    timeout_seconds: float = 30.0
    max_memory_bytes: int = 512 * 1024 * 1024  # 512MB
    max_cpu_percent: float = 100.0
    max_processes: int = 5
    max_output_bytes: int = 10 * 1024 * 1024  # 10MB


class NetworkPolicyMode(str, Enum):
    """Network egress isolation modes."""

    DISABLED = "disabled"
    RESTRICTED = "restricted"
    ALLOWED = "allowed"


@dataclass
class NetworkPolicy:
    """Network egress policy for sandboxed execution."""

    mode: NetworkPolicyMode = NetworkPolicyMode.DISABLED
    allowed_hosts: list[str] = field(default_factory=list)
    allowed_ports: list[int] = field(default_factory=list)
    allow_loopback: bool = False

    def is_allowed(self, host: str, port: int) -> bool:
        """Check if destination host and port are permitted under policy."""
        if self.mode == NetworkPolicyMode.ALLOWED:
            return True
        if self.mode == NetworkPolicyMode.DISABLED:
            return False
        # RESTRICTED mode
        if host in ("127.0.0.1", "localhost", "::1") and not self.allow_loopback:
            return False
        if self.allowed_hosts and host not in self.allowed_hosts:
            return False
        if self.allowed_ports and port not in self.allowed_ports:
            return False
        return True


@dataclass
class FilesystemPolicy:
    """Filesystem sandbox isolation rules."""

    read_paths: list[str] = field(default_factory=list)
    write_paths: list[str] = field(default_factory=list)
    temp_dir: str | None = None
    artifact_dir: str | None = None
    forbidden_paths: list[str] = field(
        default_factory=lambda: [
            ".git",
            "core",
            ".env",
            "id_rsa",
            "id_ed25519",
            "/etc/shadow",
            "/etc/passwd",
            "C:\\Windows\\System32",
        ]
    )


@dataclass
class SandboxPolicy:
    """Composite sandbox policy governing execution boundaries."""

    fs_policy: FilesystemPolicy = field(default_factory=FilesystemPolicy)
    network_policy: NetworkPolicy = field(default_factory=NetworkPolicy)
    env_allowlist: list[str] = field(
        default_factory=lambda: [
            "PATH",
            "TEMP",
            "TMP",
            "PYTHONPATH",
            "SYSTEMROOT",
            "COMSPEC",
            "PATHEXT",
        ]
    )
    seccomp_profile: str = "default"  # "default" | "strict" | "network_only"


@dataclass
class Artifact:
    """Structured artifact generated by worker capability execution."""

    artifact_id: str
    name: str
    path: str
    mime_type: str = "text/plain"
    size_bytes: int = 0
    sha256: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "artifact_id": self.artifact_id,
            "name": self.name,
            "path": self.path,
            "mime_type": self.mime_type,
            "size_bytes": self.size_bytes,
            "sha256": self.sha256,
            "metadata": self.metadata,
        }


@dataclass
class ExecutionMetrics:
    """Resource consumption metrics for an execution."""

    duration_seconds: float = 0.0
    memory_peak_bytes: int = 0
    cpu_time_seconds: float = 0.0
    process_count: int = 0


@dataclass
class ExecutionError:
    """Structured failure representation adhering to failure-taxonomy.json."""

    error_class: str
    message: str
    retryable: bool = False
    details: dict[str, Any] = field(default_factory=dict)
    attempt: int = 1
    recoverable: bool = False

    def __post_init__(self) -> None:
        if self.recoverable:
            self.retryable = True
        elif self.retryable:
            self.recoverable = True

    def to_payload(self) -> dict[str, Any]:
        """Format matching worker.tool.failed payload schema."""
        mapped_class = map_error_to_failure_taxonomy(self.error_class)
        return {
            "error_class": mapped_class,
            "message": self.message,
            "retryable": self.retryable,
            "attempt": self.attempt,
        }


@dataclass
class ExecutionRequest:
    """Request submitted to a Worker to execute an authorized capability."""

    request_id: str
    correlation_id: str
    space_id: str
    worker_id: str
    capability: str
    arguments: dict[str, Any] = field(default_factory=dict)
    lease_id: str | None = None
    resource_requirements: dict[str, Any] = field(default_factory=dict)
    execution_limits: ExecutionLimits = field(default_factory=ExecutionLimits)
    sandbox_policy: SandboxPolicy = field(default_factory=SandboxPolicy)
    idempotency_key: str | None = None
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass
class ExecutionResult:
    """Result of an executed capability."""

    request_id: str
    status: str  # "ok" | "failed" | "denied" | "timeout" | "violation" | "cancelled"
    artifacts: list[Artifact] = field(default_factory=list)
    output_data: Any = None  # Strictly passive data, never instructions (WORKER-002)
    taint: bool = False  # True if generated from external untrusted content
    metrics: ExecutionMetrics = field(default_factory=ExecutionMetrics)
    logs: list[str] = field(default_factory=list)
    error: ExecutionError | None = None

    @property
    def is_success(self) -> bool:
        return self.status == "ok" and self.error is None


@dataclass
class WorkerObservation:
    """Snapshot observation of worker execution."""

    request_id: str
    worker_id: str
    state: WorkerState
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    message: str = ""


# ---------------------------------------------------------------------------
# Failure Taxonomy Mapping (failure-taxonomy.json)
# ---------------------------------------------------------------------------

_TAXONOMY_MAP: dict[str, tuple[str, bool]] = {
    # Transient categories
    "TIMEOUT": ("transient.timeout", True),
    "transient.timeout": ("transient.timeout", True),
    "RATE_LIMIT": ("transient.rate_limit", True),
    "transient.rate_limit": ("transient.rate_limit", True),
    "NETWORK_ERROR": ("transient.network", True),
    "transient.network": ("transient.network", True),
    # Terminal categories
    "INVALID_PARAMS": ("terminal.invalid_params", False),
    "terminal.invalid_params": ("terminal.invalid_params", False),
    "PERMISSION_DENIED": ("terminal.permission_denied", False),
    "terminal.permission_denied": ("terminal.permission_denied", False),
    "LEASE_INVALID": ("terminal.permission_denied", False),
    "LEASE_EXPIRED": ("terminal.permission_denied", False),
    "FILESYSTEM_DENIED": ("terminal.permission_denied", False),
    "NETWORK_DENIED": ("terminal.permission_denied", False),
    "SECCOMP_VIOLATION": ("terminal.permission_denied", False),
    "SANDBOX_VIOLATION": ("terminal.permission_denied", False),
    "BUDGET_EXCEEDED": ("terminal.budget_exceeded", False),
    "terminal.budget_exceeded": ("terminal.budget_exceeded", False),
    "RESOURCE_EXHAUSTED": ("terminal.budget_exceeded", False),
    "NOT_FOUND": ("terminal.not_found", False),
    "terminal.not_found": ("terminal.not_found", False),
    # Process crash & others
    "PROCESS_CRASH": ("terminal.invalid_params", False),
    "WORKER_CRASH": ("terminal.invalid_params", False),
    "CANCELLED": ("terminal.permission_denied", False),
}


def map_error_to_failure_taxonomy(error_class: str) -> str:
    """Map any internal or worker error code into a standard failure-taxonomy class."""
    if error_class.startswith("transient.") or error_class.startswith("terminal."):
        return error_class
    mapping = _TAXONOMY_MAP.get(error_class)
    if mapping:
        return mapping[0]
    return "terminal.invalid_params"


def is_error_retryable(error_class: str) -> bool:
    """Determine retryability per failure-taxonomy.json."""
    if error_class.startswith("transient."):
        return True
    if error_class.startswith("terminal."):
        return False
    mapping = _TAXONOMY_MAP.get(error_class)
    if mapping:
        return mapping[1]
    return False
